[phases.setup]
nixPkgs = ["...", "default-libmysqlclient-dev"]

[phases.build]
cmds = ["bundle install --without development:test"]

[start]
cmd = "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"
